### ISSUE TITLE
Use the package.d feature

### ISSUE THREAD

**Issue by aldacron** [JordanFitz/danvas#1]
Neat project! Thought of doing something similar many times, but just too many other things to do. Looking through your code, I noticed you're using a module named 'dcanvas.all' to import all of the dcanvas modules. That old trick isn't necessary these days with the package.d feature. Simply create a file dcanvas/package.d, name in 'dcanvas' in the module statement, then put all of your public imports there. Then you can import the whole package in client code with 'import dcanvas'.

**Comment by JordanFitz** [comment]
Thanks for the information! There are quite a few features I'm planning on adding so I'll be sure to include that in the next push.

**Comment by aldacron** [comment]
Not quite right. package.d should actually be *in* the dcanvas directory, not one level above.
